spring:
  application:
    name: employees-api
  datasource:
    url: jdbc:postgresql://postgres:5432/employees
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
server:
  port: 8081
