server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true

    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: health, info