spring:
  application:
    name: workstations-api

  config:
    import: "consul:"

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8082